version: '2'
services:
  web:
    build: .
    env_file:
      - ./config/docker.env
    depends_on:
      - db
  db:
    image: postgres:9.5
    volumes:
      - "pgdata:/var/lib/postgresql/data"

  proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"

volumes:
  pgdata:
